### ISSUE TITLE
Symbol Server does not handle escaped plus signs

### ISSUE THREAD

**Issue by Marc-Aldorasi-Imprivata** [JetBrains/teamcity-symbol-server#12]
When getting symbols for dlls with `+` characters in their name, WinDbg escapes the plus into `%2b` when sending the request (e.g. `https://teamcity.example.com/app/symbols/file%2b%2b.dll/123456789000/file%2b%2b.dll`).  The symbol server plugin returns a 404 error in these cases, but a request with unescaped plusses (e.g. `https://teamcity.example.com/app/symbols/file++.dll/123456789000/file++.dll`) works.  These requests should be treated the same.

**Comment by dtretyakov** [comment]
@marc-groundctl, thanks for reporting. It was fixed in the latest plugin build: https://github.com/JetBrains/teamcity-symbol-server#download
