### ISSUE TITLE
Visual Studio cannot retrieve symbols

### ISSUE THREAD

**Issue by lestera** [JetBrains/teamcity-symbol-server#16]
Hi,

Since updating the symbol server to the latest 2018.1.x version, Visual Studio is no longer able to retrieve symbols automatically.

From TeamCity's `symbol-signature-artifacts.xml` (replaced the hash with X's - 32 total):

> &lt;file-sign-entry sign="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" file="File.pdb" file-path="path/to/File.pdb"/&gt;

From Visual Studio's "Symbol Load Information" dialog (replaced the hash with X's - 33 total):

> https://teamcity.server.com/app/symbols: Symbols not found on symbol server.
> SYMSRV:  BYINDEX: 0x43
>          D:\Path\To\SymbolCache*https://msdl.microsoft.com/download/symbols
>          File.pdb
>          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

I think commit https://github.com/JetBrains/teamcity-symbol-server/commit/df38b5a72c4480eeac2d08dbaa57f9f2ae746f7f is what caused it to break.
Truncating the GUID to 32 characters causes Visual Studio to fail retrieving the symbol, as it looks for a 33 character symbol.

**Comment by coridrew** [comment]
Updating to latest plugin broke downloading symbols for us, as well. We're on TeamCity Enterprise 2018.1.3. Installing The latest from master, and the prior plugin version, both show artifacts like they index properly, but we cannot download to Visual Studio, or from the /app/symbols/name.pdb/guid/name.pdb directly.  Using a symbol-server.zip from August reenabled ability to download directly from /app/symbols/name.pdb/guid#/name.pdb link, but still unable to get symbols in Visual Studio.

**Comment by lestera** [comment]
For reference, I've also opened an issue here: https://teamcity-support.jetbrains.com/hc/en-us/requests/1883203

**Comment by coridrew** [comment]
> 1883203

That link returns a 404 for me.

**Comment by coridrew** [comment]
> > 1883203
> 
> That link returns a 404 for me.

Although now I see why, as I've opened https://teamcity-support.jetbrains.com/hc/en-us/requests/1885051 for our issue.

**Comment by dtretyakov** [comment]
@lestera, @coridrew, thanks for reporting. The breaking change was reverted, please try updating to the latest plugin build: https://plugins.jetbrains.com/plugin/9123-symbol-server-support and let me know if it resolves the problem.

**Comment by lestera** [comment]
@dtretyakov That seems to have solved the issue. Thanks!

**Comment by coridrew** [comment]
Yes, thank you!
