### ISSUE TITLE
Request: ability to override base url for sources

### ISSUE THREAD

**Issue by OlduwanSteve** [JetBrains/teamcity-symbol-server#2]
Hi, further to this post:

https://teamcity-support.jetbrains.com/hc/en-us/community/posts/207580705-Source-server-plugin-custom-url

I'd like the source url injected into the pdbs to be http instead of https, but my main teamcity url has to be https. Would it be possible to look for a build parameter (or add configuration to the build feature itself) to override the default 'base' url for sources?

I don't mind having a go at implementing this, but right now I can't get the plugin to build, due to this error:

`Error:(34, 28) java: [path to build]teamcity-symbol-server\agent\src\jetbrains\buildServer\symbols\ArtifactPathHelper.java:34: shouldProcess(java.lang.String) has private access in jetbrains.buildServer.agent.impl.artifacts.ArchivePreprocessor`

**Comment by OlduwanSteve** [comment]
In fact as I only have the community edition of intellij, I'm not sure I can build this in any case.

**Comment by ghost** [comment]
Hi, suggested way to override baseUrl looks good to me. Nice to hear that you would like to contribute!
As for that error. Please make sure you are developing symbol-server plugin using correct version of TeamCity distributive.

**Comment by OlduwanSteve** [comment]
I looked at the code again and it looks like I should have tried:

symbols.server-own-url

Which seems to do exactly what I wanted.
