### ISSUE TITLE
SymbolsIndexer executes when the build feature is not enabled

### ISSUE THREAD

**Issue by lnavarette** [JetBrains/teamcity-symbol-server#9]
**Actual Behavior**
In the case where multiple configurations are run on the same agent, `myFileUrlProvider` and `mySrcSrvHomeDir` can be set on `SymbolsIndexer` by a build that has the feature enabled, then a later build with the feature disabled will still attempt to index files. 

On build start, the plugin does check whether the feature is enabled, and in that case, exits earlier. 
```
if(runningBuild.getBuildFeaturesOfType(SymbolsConstants.BUILD_FEATURE_TYPE).isEmpty()){
  LOG.debug(SymbolsConstants.BUILD_FEATURE_TYPE + " build feature disabled. No indexing will be performed for build with id " + buildId);
  return;
}
```

However, on build finish it checks only that the indexer was initialized, not that the feature is enabled:
```
private boolean isIndexingApplicable() {
    return myFileUrlProvider != null && mySrcSrvHomeDir != null;
}
```

**Expected Behavior**
`SymbolsIndexer` should never be executed on builds with the feature disabled.

**Comment by dtretyakov** [comment]
@lnavarette, you could download the [latest plugin build](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamCityPluginsByJetBrains_SymbolServer_BuildTrunk).
